### ISSUE TITLE
Where can I get a token to run this app?

### ISSUE THREAD

**Issue by sw5813** [ActiveLook/demo-app#2]
It looks like the latest update to this demo app requires an ActiveLook SDK token- where can I get this token?

**Comment by SylvainRomillon** [comment]
I will add it to the readme.
This field needs to be left blank by default.
The SDK Token is only useful for (and provided to) eyewear partners developing their own ActiveLook application. It allows the partner application to be authenticated by the ActiveLook update server and to update Firwmware and / or system configuration (Alook) onto any ActiveLook-powered eyewear.
Leaving the field blank will allow app compilation without requiring an access to the update server.

**Comment by sw5813** [comment]
Deleting the "ACTIVELOOK_SDK_TOKEN =" line from the Config works for me and I'm able to run the demo app- thanks!
